# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Watchill' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Watchill

end

target 'Watchill WatchKit App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Watchill WatchKit App

end

target 'Watchill WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Watchill WatchKit Extension

end
